spring:
  application:
    name: rent-a-car

  jackson:
    serialization.fail-on-empty-beans: false

  transaction.default-timeout: 30

  datasource:
    url: jdbc:h2:file:./src/main/resources/db/rent-a-car-db
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: true
    properties:
      hibernate.ddl-auto: validate
      hibernate.id.db_structure_naming_strategy: single

  flyway:
    out-of-order: true
